"""
CreativityOutputSchema

This schema represents the creative output generated by cognitive processes,
including novel ideas, combinations, and transformations.
"""

from lux_sdk.signals import SignalSchema

CreativityOutputSchema = SignalSchema(
    name="creativity_output",
    version="1.0",
    description="Schema for representing creative outputs from cognitive processes",
    schema={
        "type": "object",
        "properties": {
            "timestamp": {"type": "string", "format": "date-time"},
            "output_id": {"type": "string"},
            "type": {
                "type": "string",
                "enum": ["idea", "combination", "transformation", "analogy", "synthesis"]
            },
            "content": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "description": {"type": "string"},
                    "elements": {
                        "type": "array",
                        "items": {"type": "string"}
                    }
                },
                "required": ["title", "description"]
            },
            "source_concepts": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "concept_id": {"type": "string"},
                        "contribution": {"type": "string"}
                    },
                    "required": ["concept_id"]
                }
            },
            "novelty_score": {
                "type": "number",
                "minimum": 0.0,
                "maximum": 1.0,
                "description": "Estimated novelty of the output from 0.0 (common) to 1.0 (highly novel)"
            },
            "metadata": {
                "type": "object",
                "properties": {
                    "context": {"type": "string"},
                    "tags": {"type": "array", "items": {"type": "string"}},
                    "related_outputs": {"type": "array", "items": {"type": "string"}}
                }
            }
        },
        "required": ["timestamp", "output_id", "type", "content", "novelty_score"]
    }
) 