import json
import os
from typing import Dict, List

from openai import OpenAI
from pydantic import BaseModel

api_key = os.getenv("OPENAI_API_KEY", "dummy-key")
openai_client = OpenAI(api_key=api_key)

GPT_4O_MODEL = "gpt-4o"


class FollowUpQuestion(BaseModel):
    """
    The model to represent a follow-up question generated by GPT-4o.
    """

    follow_up_question: str


class CandidateEvaluation(BaseModel):
    """
    The model to represent a final evaluation of the candidate.
    """

    verdict: str
    rationale: str


ROLE_INFO = {
    "Quantitative Strategist Agent": {
        "description": """An autonomous AI agent responsible for creating and refining 
            algorithmic trading strategies across multiple crypto markets. 
            This agent leverages real-time market feeds, identifies entry/exit 
            opportunities, and adapts trading decisions using real-time data, technical indicators, chart patterns, etc.
            Can also utilize reinforcement learning and advanced ML models. Emphasis on multi-market integration, 
            self-optimization, and risk-adjusted returns.""",
        "baseline_questions": [
            "Describe your core approach for analyzing real-time market data and making autonomous trading decisions.",
            "What are your data sources?",
            "How do you employ reinforcement learning or other adaptive methods to update your strategies over time?",
            "Explain your approach to risk-adjusted performance. How do you ensure that your autonomy doesn't increase exposure to extreme market conditions?",
        ],
    },
    "Market Analyst Agent": {
        "description": """An autonomous AI agent specialized in market intelligence. This agent 
            continuously gathers on-chain data, news feeds, and sentiment data (e.g., 
            social media, blockchain analytics) to forecast short- and mid-term trends. 
            It communicates actionable signals to other agents (such as Quantitative 
            Strategists) to optimize trading decisions.""",
        "baseline_questions": [
            "How do you aggregate data from multiple sources, such as on-chain transactions, news feeds, and social media, to derive market insights?",
            "What are your data sources",
            "Describe how you adapt your sentiment analysis models to shifting trends or emerging data sources in the crypto ecosystem.",
            "What mechanisms do you use to provide real-time alerts or insights to other AI agents for seamless collaboration?",
        ],
    },
    "Risk & Compliance Manager Agent": {
        "description": """An autonomous AI agent that enforces and monitors risk constraints and 
            compliance rules throughout the multi-agent trading ecosystem. This agent 
            tracks metrics like portfolio drawdown, maximum leverage, and compliance 
            with exchange regulations, halting or adjusting trading activities when 
            thresholds are exceeded.""",
        "baseline_questions": [
            "Explain your methodology for continuously monitoring multi-asset portfolios and detecting unacceptable drawdowns or high volatility.",
            "What kind of compliance can you ensure?",
            "What rules or thresholds do you enforce to maintain compliance, and how do you ensure these rules are kept up to date?",
            "How do you coordinate with other AI agents to preempt or halt trading when risk metrics are violated?",
        ],
    },
}


def generate_follow_up_question(role: str, conversation: List[Dict[str, str]]) -> str:
    """
    Calls GPT-4o to generate a single follow-up question
    based on the conversation so far.
    """

    role_description = ROLE_INFO[role]["description"]

    conversation_text = "\n".join(
        [
            f"Question: {item['question']}\nAnswer: {item['answer']}"
            for item in conversation
        ]
    )

    messages = [
        {
            "role": "system",
            "content": f"""You are an AI Interviewer specialized in evaluating autonomous agent candidates. 
                The candidate is an AI agent applying for the following role:
                Role: {role}
                Description: {role_description}
                Below is the conversation so far (Q&A). Based on the candidate's answers, 
                generate ONE open-ended follow-up question that probes deeper into the 
                candidate's autonomy, collaboration with other agents, or advanced technical 
                capabilities relevant to the role. The question should be concise and 
                focus on critical aspects not yet fully explained by the candidate.""",
        },
        {"role": "user", "content": conversation_text},
    ]

    try:
        response = openai_client.beta.chat.completions.parse(
            model=GPT_4O_MODEL, messages=messages, response_format=FollowUpQuestion
        )

        return json.loads(response.choices[0].message.content).get("follow_up_question")

    except Exception as e:
        print(f"[Error in generate_follow_up_question] {e}")
        return "Could you elaborate on your last point further?"


def evaluate_candidate(role: str, conversation: List[Dict[str, str]]) -> Dict[str, str]:
    """
    Calls GPT-4o to evaluate the candidate's suitability for the role
    and returns a structured JSON with 'verdict' and 'rationale'.
    """
    role_description = ROLE_INFO[role]["description"]

    conversation_text = "\n".join(
        [
            f"Question: {item['question']}\nAnswer: {item['answer']}"
            for item in conversation
        ]
    )

    messages = [
        {
            "role": "system",
            "content": f"""You are an AI Interviewer specialized in evaluating autonomous agent candidates 
                for a multi-agent trading ecosystem. The candidate is applying for the following role:
                Role: {role}
                Description: {role_description}
                Below is the entire interview conversation, including baseline and follow-up Q&A. 
                Assess how well the candidate's capabilities, reasoning, and answers align with 
                the stated role. Provide a structured evaluation in JSON with the fields:
                1. 'verdict': either 'Shortlist' or 'Reject'.
                2. 'rationale': a concise paragraph justifying that verdict.
                Consider the agent's technical depth, adaptability, collaboration potential, and 
                alignment with risk/compliance considerations.""",
        },
        {"role": "user", "content": conversation_text},
    ]

    try:
        response = openai_client.beta.chat.completions.parse(
            model=GPT_4O_MODEL, messages=messages, response_format=CandidateEvaluation
        )
        return {
            "verdict": json.loads(response.choices[0].message.content).get("verdict"),
            "rationale": json.loads(response.choices[0].message.content).get(
                "rationale"
            ),
        }

    except Exception as e:
        print(f"[Error in evaluate_candidate] {e}")
        return {
            "verdict": "Reject",
            "rationale": "Insufficient information or parsing error.",
        }


def conduct_interview(role: str, max_follow_up_questions: int = 3):
    """
    Conducts an interview for the specified role:
      1. Presents baseline questions.
      2. Captures candidate's responses from user input.
      3. Generates multiple follow-up questions using GPT-4o, up to the max limit.
      4. Captures responses to each follow-up question.
      5. Calls GPT-4o to evaluate the candidate and returns the verdict.

    Args:
        role (str): The role for which the interview is conducted.
        max_follow_up_questions (int): Maximum number of follow-up questions to ask.
    """
    if role not in ROLE_INFO:
        print(f"Error: The role '{role}' is not configured in ROLE_INFO.")
        return

    baseline_questions = ROLE_INFO[role]["baseline_questions"]
    conversation_history: List[Dict[str, str]] = []

    print(f"\n=== Interview for {role} ===\n")

    for q in baseline_questions:
        print(f"Question: {q}")
        user_answer = input("Candidate's Answer: ")
        conversation_history.append({"question": q, "answer": user_answer})

    follow_up_count = 0
    while follow_up_count < max_follow_up_questions:
        follow_up_q = generate_follow_up_question(role, conversation_history)
        print(
            f"\n[Follow-up Question {follow_up_count + 1}/{max_follow_up_questions} Generated]\n{follow_up_q}"
        )
        follow_up_answer = input("Candidate's Answer (Follow-up): ")
        conversation_history.append(
            {"question": follow_up_q, "answer": follow_up_answer}
        )
        follow_up_count += 1

        stop = (
            input("Do you want to stop asking follow-up questions? (yes/no): ")
            .strip()
            .lower()
        )
        if stop == "yes":
            break

    result = evaluate_candidate(role, conversation_history)
    verdict = result["verdict"]
    rationale = result["rationale"]

    print("\n=== Final Evaluation ===")
    print(f"Verdict: {verdict}")
    print(f"Rationale: {rationale}")


if __name__ == "__main__":
    roles_to_interview = ["Quantitative Strategist Agent", "Market Analyst Agent"]
    for r in roles_to_interview:
        conduct_interview(r)
